name: crypto_model
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  aurora_mail:
    path: ../../..
dev_dependencies:
  flutter_test:
    sdk: flutter

