name: crypto_worker_impl
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto_model:
    path: ../crypto_model
  crypto_worker:
    path: ../crypto_worker
  crypto_storage:
    path: ../crypto_storage
  crypto_stream:
    git:
      url: https://github.com/afterlogic/flutter_crypto_stream
      ref: flutter_3.3
  path_provider: 2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
