name: crypto_worker
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto_model:
    path: ../crypto_model
dev_dependencies:
  flutter_test:
    sdk: flutter