name: crypto_storage_impl
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto_model:
    path: ../crypto_model
  crypto_storage:
    path: ../crypto_storage
  flutter_secure_storage: ^3.3.1+1
  moor_flutter: ^2.0.0
  #move all db to module
  aurora_mail:
    path: ../../..
dev_dependencies:
  flutter_test:
    sdk: flutter
