name: aurora_mail
description: Mail client for mobile.

version: 0.0.11+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1

  # state management
  flutter_bloc: ^3.1.0
  equatable: ^1.0.2

  # http
  http: ^0.12.0+4
  webmail_api_client:
    path: ./core/webmail_api_client

  # local storage
  moor_flutter: ^2.0.0
  shared_preferences: ^0.5.6

  # file downloading/uploading
  file_picker: 1.4.3+2
  flutter_uploader: ^1.2.0
  flutter_downloader: ^1.3.4
  path_provider: ^1.5.1

  # type ahead
  flutter_typeahead: ^1.7.0

  # ui
  material_design_icons_flutter: ^3.4.4795
  webview_flutter: ^0.3.19+3
  flutter_speed_dial: ^1.2.5
  empty_list:
    git:
      url: git://github.com/VadimOsovsky/flutter_empty_list.git

  # i18n
  flutter_i18n: ^0.8.3

  # misc
  uuid: ^2.0.4
  intl: ^0.16.0
  filesize: ^1.0.4
  permission_handler: ^4.0.0
  url_launcher: ^5.4.1
  connectivity: ^0.4.6+2
  package_info: ^0.4.0+13

  #background
#  android_alarm_manager: 0.4.5+1 not working
  alarm_service:
    path: alarm_service


  #notification
  flutter_local_notifications: 0.8.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.3
  moor_generator: ^2.2.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/flutter_i18n/

  fonts:
    - family: WebMailIcons
      fonts:
        - asset: assets/fonts/WebMailIcons.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
