name: aurora_mail
description: Mail client for mobile.

#version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations:

  # state management
  flutter_bloc:
  equatable:
  #  provider:

  # http
  http:
  webmail_api_client:
    path: ./core/webmail_api_client

  # local storage
  moor_flutter:
  shared_preferences:

  # file downloading/uploading
  file_picker:
  flutter_uploader:
  flutter_downloader:
  path_provider:
  downloads_path_provider:

  # type ahead
  flutter_typeahead:

  # ui
  material_design_icons_flutter:
  animated_stream_list:
  webview_flutter:
  flutter_speed_dial:
  empty_list:
    git:
      url: git://github.com/VadimOsovsky/flutter_empty_list.git

  # i18n
  flutter_i18n:

  # misc
  uuid:
  intl:
  filesize:
  permission_handler:
  url_launcher:
  connectivity:
  package_info:

  #background
#  android_alarm_manager: 0.4.5+1 not working
  alarm_service:
    path: alarm_service


  #notification
  flutter_local_notifications: 0.8.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

  build_runner:
  moor_generator:

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/flutter_i18n/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
