name: aurora_mail
description: Mail client for mobile.

version: 2.0.0+50

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1

  # state management
  flutter_bloc: ^3.2.0
  equatable: ^1.0.2

  # http
  http: ^0.12.0+4
  webmail_api_client:
    path: ./core/webmail_api_client

  # local storage
  moor_flutter: ^2.0.0
  shared_preferences: ^0.5.6

  # file downloading/uploading
  file_picker: ^1.4.3+2
  flutter_uploader: ^1.2.0
  flutter_downloader: ^1.4.0
  esys_flutter_share: ^1.0.2
  path_provider: ^1.5.1

  # type ahead
  flutter_typeahead: ^1.7.0

  # ui
  material_design_icons_flutter: ^3.4.4895
  webview_flutter: ^0.3.19+5
  flutter_speed_dial: ^1.2.5
  fluttertoast: ^3.1.3
  shimmer: ^1.0.1

  # i18n
  flutter_i18n: ^0.8.3

  # misc
  uuid: ^2.0.4
  intl: ^0.16.0
  filesize: ^1.0.4
  permission_handler: ^4.2.0+hotfix.3
  url_launcher: ^5.4.1
  connectivity: ^0.4.6+2
  package_info: ^0.4.0+13

  # crashlytics
  firebase_crashlytics: ^0.1.2+5

  #background
  #  android_alarm_manager: 0.4.5+1 not working
  alarm_service:
    path: alarm_service

  notifications_utils:
    path: core/notifications_utils

  aurora_ui_kit:
    git: https://github.com/afterlogic/aurora_ui_kit_flutter.git


  #notification
  flutter_local_notifications: 0.8.4+3

  keyboard_actions: ^3.2.0

  theme:
    path: build_res/private_mail/theme

  crypto_model:
    path: module/crypto/crypto_model
  crypto_storage:
    path: module/crypto/crypto_storage
  crypto_worker:
    path: module/crypto/crypto_worker
  flutter_secure_storage: ^3.3.1+1
  crypto_plugin:
    git: https://github.com/afterlogic/flutter_crypto_plugin
  crypto_storage_impl:
    path: module/crypto/crypto_storage_impl
  crypto_worker_impl:
    path: module/crypto/crypto_worker_impl

  inject:
    git: "https://github.com/afterlogic/dart_inject"

dev_dependencies:
  flutter_test:
    sdk: flutter
  inject_generator:
    git: "https://github.com/afterlogic/inject_generator"
  build_runner: ^1.7.3
  moor_generator: ^2.3.1
  build_variant:
    git: "https://github.com/afterlogic/build_variant"
  flutter_launcher_icons: 0.7.4

flutter_icons:
  ios: true
  android: true
  image_path: build_res/private_mail/icon.png
  adaptive_icon_background: "#34113C"
  adaptive_icon_foreground: build_res/private_mail/icon_foreground.png

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/flutter_i18n/
    - build_res/private_mail/icon.png
    - build_res/private_mail/image/main_logo.png
    - build_res/private_mail/image/

  fonts:
    - family: WebMailIcons
      fonts:
        - asset: assets/fonts/WebMailIcons.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
