name: aurora_mail
description: Mail client for mobile.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state management
  mobx: ^0.3.5
  flutter_mobx: ^0.3.0+1
  provider: ^2.0.0

  # http
  http: ^0.12.0+2

  # local storage
  moor_flutter: ^1.6.0
  shared_preferences: ^0.5.3+4

  # ui
  cupertino_icons: ^0.1.2
  material_design_icons_flutter: ^3.2.4096
  animated_stream_list: ^1.0.0

  # misc
  uuid: ^2.0.2
  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.6.5
  mobx_codegen: ^0.3.3+1
  moor_generator: ^1.6.0+2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
