name: aurora_mail
description: Mail client for Aurora Mail.

version: "2.3.5+278"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  firebase_core_platform_interface: ^4.5.3
#  flutter_cupertino_localizations: 1.0.1
  table_calendar: ^3.0.8

  # state management
  provider: ^5.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.5
  rxdart: ^0.27.7

  # http
  http: 0.13.3
  webmail_api_client:
    path: ./core/webmail_api_client
  html: ^0.15.0

  # local storage
  drift_sqflite: ^1.0.0
  shared_preferences: ^2.1.1

  # file downloading/uploading
  file_picker: 5.2.10
  flutter_uploader: 3.0.0-beta.4
  flutter_downloader: 1.10.5
  share: ^2.0.4
  path_provider: 2.0.2
  video_thumbnail: 0.5.3
  mime: ^1.0.1
  # type ahead

  # ui
  flutter_svg: ^1.1.6
  material_design_icons_flutter: ^7.0.7296
  webview_flutter: ^4.0.7
  flutter_speed_dial: ^7.0.0
  fluttertoast: 8.2.2
  shimmer: ^3.0.0

  # i18n
#  localizator_interface: 0.4.0
  # misc
  uuid: ^4.1.0
  intl: 0.17.0
  filesize: ^2.0.1
  permission_handler: ^11.0.0
  permission_handler_platform_interface: ^3.11.5
  url_launcher: ^6.1.10
  connectivity: 3.0.6
  package_info: ^2.0.2
  time_machine: ^0.9.17
  device_info_plus: ^8.2.2
  uni_links: ^0.5.1
  flutter_custom_tabs: ^1.0.4
  # crashlytics
  firebase_core: ^2.8.0
  firebase_crashlytics: ^3.0.17
  firebase_messaging: ^14.0.2
  # file encryption
  encrypt:

  #background
  #  android_alarm_manager: 0.4.5+1 not working
  alarm_service:
    path: alarm_service

  notifications_utils:
    path: core/notifications_utils

  aurora_ui_kit:
    git:
      url: https://github.com/afterlogic/aurora_ui_kit_flutter.git

  receive_sharing:
    git:
      url: https://github.com/afterlogic/receive_sharing.git
      ref: flutter_3

  #notification
  flutter_local_notifications: ^9.5.3+1
  ios_notification_handler:
    path: core/ios_notification_handler
  keyboard_actions: ^4.2.0
#  flutter_keyboard_visibility: 0.7.0

  theme:
    path: build_res/afterlogic/theme

  crypto_model:
    path: module/crypto/crypto_model
  crypto_storage:
    path: module/crypto/crypto_storage
  crypto_worker:
    path: module/crypto/crypto_worker
  flutter_secure_storage: ^4.2.1
  crypto_stream:
    git:
      url: https://github.com/afterlogic/flutter_crypto_stream
      ref: flutter_3.3
  crypto_storage_impl:
    path: module/crypto/crypto_storage_impl
  crypto_worker_impl:
    path: module/crypto/crypto_worker_impl

  dm: ^0.4.0

  # fido
  yubico_flutter:
    path: module/mocks/yubico_flutter
  # logger
  aurora_logger:
    git:
      url: https://github.com/afterlogic/aurora_logger_flutter
      ref: master
  calendar_view: ^1.2.0
  collection: ^1.17.0
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#  dm_gen should be commented for moor_generator/drift_dev work
#  dm_gen: ^0.5.1+1
  build_runner: ^2.3.3
  drift_dev: ^1.7.1
  build_variant:
    git:
      url: "https://github.com/afterlogic/build_variant"
      ref: master

  flutter_launcher_icons: ^0.11.0
#  localizator: ^0.4.2

#dependency_overrides:
#  analyzer: 5.2.0
#  build: 2.1.0
#  meta: ^1.7.0
#  dart_style: 2.2.0
#  moor: 4.4.0

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: build_res/afterlogic/image/icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: build_res/afterlogic/image/icon_foreground.png

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - build_res/afterlogic/image/icon.png
    - build_res/afterlogic/image/main_logo.png
    - build_res/afterlogic/image/

  fonts:
    - family: WebMailIcons
      fonts:
        - asset: assets/fonts/WebMailIcons.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
