name: aurora_mail
description: Mail client for mobile.

#version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations:

  # state management
  flutter_bloc:
  equatable:
  #  provider:

  # http
  http:
  webmail_api_client:
    path: ./core/webmail_api_client

  # local storage
  moor_flutter:
  shared_preferences:

  # file downloading/uploading
  file_picker:
  flutter_uploader:
  flutter_downloader:
  path_provider:
  downloads_path_provider:

  # ui
  material_design_icons_flutter:
  animated_stream_list:
  webview_flutter:

  # misc
  uuid:
  intl:
  filesize:
  permission_handler:
  url_launcher:
  connectivity:
  package_info:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

  build_runner:
  moor_generator:

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
