name: aurora_mail
description: Mail client for PrivateMail.

version: 2.7.2+225

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: 1.0.1

  # state management
  provider: 4.3.2+2
  flutter_bloc: 3.2.0
  equatable: 1.1.1

  # http
  http: 0.12.0+4
  webmail_api_client:
    path: ./core/webmail_api_client

  # local storage
  moor_flutter: 2.1.1
  shared_preferences: 0.5.6+3

  # file downloading/uploading
  file_picker: 4.0.0
  flutter_uploader: 1.2.0
  flutter_downloader: 1.5.2
  share: 0.6.5+4
  path_provider: 2.0.2
  video_thumbnail: 0.2.1
  mime: 0.9.7
  # type ahead
  flutter_typeahead: 1.8.0

  # ui
  flutter_svg: 0.21.0
  material_design_icons_flutter: 3.4.5045+1
  webview_flutter: 1.0.7
  flutter_speed_dial: 1.2.5
  fluttertoast: 3.1.3
  shimmer: 1.1.0

  # i18n
  localizator_interface: 0.4.0
  # misc
  uuid: 2.0.4
  intl: 0.17.0
  filesize: 1.0.4
  permission_handler: 8.1.4+2
  permission_handler_platform_interface: 3.6.1
  url_launcher: 6.0.9
  connectivity: 3.0.6
  package_info: 0.4.0+16
  time_machine: 0.9.16
  device_id: 0.2.0
  device_info: 2.0.2
  uni_links: 0.4.0
  flutter_custom_tabs: 1.0.3
  # crashlytics
  firebase_core:
  firebase_crashlytics: 2.2.0
  firebase_messaging: 10.0.5
  # file encryption
  encrypt:

  #background
  #  android_alarm_manager: 0.4.5+1 not working
  alarm_service:
    path: alarm_service

  notifications_utils:
    path: core/notifications_utils

  aurora_ui_kit:
    git: https://github.com/afterlogic/aurora_ui_kit_flutter.git

  receive_sharing:
    git: https://github.com/afterlogic/receive_sharing

  #notification
  flutter_local_notifications: 8.1.1+1
  ios_notification_handler:
    path: core/ios_notification_handler
  keyboard_actions: 3.2.0

  theme:
    path: aurora-mail-app-customs/private_mail/theme

  crypto_model:
    path: module/crypto/crypto_model
  crypto_storage:
    path: module/crypto/crypto_storage
  crypto_worker:
    path: module/crypto/crypto_worker
  flutter_secure_storage: 3.3.1+1
  crypto_stream:
    git:
      url: https://github.com/afterlogic/flutter_crypto_stream
      ref: master
  crypto_storage_impl:
    path: module/crypto/crypto_storage_impl
  crypto_worker_impl:
    path: module/crypto/crypto_worker_impl

  dm: 0.1.0

  # fido
  yubico_flutter:
    git: https://github.com/afterlogic/yubico_flutter
  # logger
  aurora_logger:
    git: https://github.com/afterlogic/aurora_logger_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  dm_gen: 0.1.0
  build_runner: 1.8.1
  moor_generator: 2.4.0
  build_variant:
    git: "https://github.com/afterlogic/build_variant"
  flutter_launcher_icons: 0.7.4
  localizator: 0.4.0
flutter_icons:
  ios: true
  android: true
  image_path: aurora-mail-app-customs/private_mail/image/icon.png
  adaptive_icon_background: "#34113C"
  adaptive_icon_foreground: aurora-mail-app-customs/private_mail/image/icon_foreground.png
dependency_overrides:
  yaml: ^2.1.15
  dart_style: ^1.0.0
  image: ^2.1.1
  xml: ^4.2.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - aurora-mail-app-customs/private_mail/image/icon.png
    - aurora-mail-app-customs/private_mail/image/main_logo.png
    - aurora-mail-app-customs/private_mail/image/

  fonts:
    - family: WebMailIcons
      fonts:
        - asset: assets/fonts/WebMailIcons.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
