name: aurora_mail
description: Mail client for mobile.

#version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1

  # state management
  flutter_bloc: ^1.0.0
  equatable: ^0.6.1
  #  provider: ^3.0.0

  # http
  http: ^0.12.0+2

  # local storage
  moor_flutter: ^1.6.0
  shared_preferences: ^0.5.3+4

  # file downloading/uploading
  file_picker: ^1.4.2
  flutter_uploader: ^1.1.0
  flutter_downloader: ^1.3.3
  path_provider: 1.2.0
  downloads_path_provider: ^0.1.0

  # ui
  material_design_icons_flutter: ^3.2.4096
  animated_stream_list: ^1.0.0
  flutter_html: ^0.11.0
  webview_flutter: ^0.3.15+1
  cookie_jar: ^1.0.0

  # misc
  uuid: ^2.0.2
  intl: ^0.15.8
  filesize: ^1.0.4
  permission_handler: ^3.2.2
  url_launcher: ^5.2.5
  connectivity: ^0.4.5+3
  package_info: ^0.4.0+12

  #background
  android_alarm_manager: ^0.4.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.6.5
  moor_generator: ^1.6.0+2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
