import 'package:aurora_mail/modules/contacts/contacts_domain/models/contact_model.dart';

class ContactMapper {
  static List<Contact> fromNetwork(List<Map<String, dynamic>> rawItems) {
    return rawItems.map((i) {
      return new Contact(
        entityId: i["EntityId"],
        uuid: i["UUID"],
        parentUuid: i["ParentUUID"],
        idUser: i["IdUser"],
        idTenant: i["IdTenant"],
        storage: i["Storage"],
        fullName: i["FullName"],
        useFriendlyName: i["UseFriendlyName"],
        primaryEmail: i["PrimaryEmail"],
        primaryPhone: i["PrimaryPhone"],
        primaryAddress: i["PrimaryAddress"],
        viewEmail: i["ViewEmail"],
        title: i["Title"],
        firstName: i["FirstName"],
        lastName: i["LastName"],
        nickName: i["NickName"],
        skype: i["Skype"],
        facebook: i["Facebook"],
        personalEmail: i["PersonalEmail"],
        personalAddress: i["PersonalAddress"],
        personalCity: i["PersonalCity"],
        personalState: i["PersonalState"],
        personalZip: i["PersonalZip"],
        personalCountry: i["PersonalCountry"],
        personalWeb: i["PersonalWeb"],
        personalFax: i["PersonalFax"],
        personalPhone: i["PersonalPhone"],
        personalMobile: i["PersonalMobile"],
        businessEmail: i["BusinessEmail"],
        businessCompany: i["BusinessCompany"],
        businessAddress: i["BusinessAddress"],
        businessCity: i["BusinessCity"],
        businessState: i["BusinessState"],
        businessZip: i["BusinessZip"],
        businessCountry: i["BusinessCountry"],
        businessJobTitle: i["BusinessJobTitle"],
        businessDepartment: i["BusinessDepartment"],
        businessOffice: i["BusinessOffice"],
        businessPhone: i["BusinessPhone"],
        businessFax: i["BusinessFax"],
        businessWeb: i["BusinessWeb"],
        otherEmail: i["OtherEmail"],
        notes: i["Notes"],
        birthDay: i["BirthDay"],
        birthMonth: i["BirthMonth"],
        birthYear: i["BirthYear"],
        eTag: i["ETag"],
        auto: i["Auto"],
        frequency: i["Frequency"],
        dateModified: i["DateModified"],
        davContactsUid: i["DavContacts::UID"],
        davContactsVCardUid: i["DavContacts::VCardUID"],
        groupUUIDs: i["GroupUUIDs"],
      );
    });
  }
}
