/// Flutter icons WebMailIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WebMailIcons
///      fonts:
///       - asset: fonts/WebMailIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WebMailIcons {
  WebMailIcons._();

  static const _kFontFam = 'WebMailIcons';

  static const IconData unshare = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData personal = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData shared_with_all = const IconData(0xe802, fontFamily: _kFontFam);
}
