name: webmail_api_client
description: HTTP client, designed to work with Afterlogic WebMail API.
version: 0.0.1
author: Afterlogic
homepage: https://afterlogic.com/webmail-pro-8-webapi/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
