import "s.dart";

class EnS extends S {
  final _map = <int, String>{
    0: "Mail Client",
    1: "Host",
    2: "Email",
    3: "Password",
    4: "Log in to continue",
    5: "No folders",
    6: "Inbox",
    7: "Starred",
    8: "Sent",
    9: "Drafts",
    10: "Spam",
    11: "Trash",
    12: "Reply",
    13: "Reply to all",
    14: "Forward",
    15: "No messages",
    16: "Unread messages:",
    17: "Delete message",
    301: "Delete messages",
    18: "Are you sure you want to delete {subject}?",
    19: "Are you sure you want to delete this message?",
    302: "Are you sure you want to delete these messages?",
    391: "Mail",
    21: "Contacts",
    22: "Settings",
    23: "Log out",
    24: "Search",
    25: "Loading folders...",
    26: "Show details",
    27: "Pictures in this message have been blocked for your safety.",
    28: "Show pictures.",
    29: "Always show pictures in messages from this sender.",
    30: "Attachments",
    31: "Message body",
    32: "To",
    33: "From",
    34: "CC",
    35: "BCC",
    36: "Subject",
    37: "No subject",
    38: "To me",
    39: "No recipients",
    40: "No sender",
    41: "No recipient",
    42: "Sending message...",
    43: "Message saved in drafts",
    44: "No attachments",
    45: "Delete attachment",
    46: "Download attachment",
    47: "Downloading {fileName}...",
    48: "Download failed",
    49: "Cancel download",
    50: "File downloaded into: {path}",
    51: "Upload attachment",
    52: "Uploading {fileName}...",
    53: "Upload failed",
    54: "Cancel upload",
    55: "File uploaded into: {path}",
    56: "Message text...",
    57: "---- Original Message ----",
    58: "From: {emails}",
    59: "To: {emails}",
    60: "CC: {emails}",
    61: "BCC: {emails}",
    62: "Sent: {date}",
    63: "Subject: {subject}",
    64: "On {time}, {from} wrote:",
    65: "Discard changes",
    66: "Save changes in drafts?",
    67: "Contacts",
    68: "View group",
    69: "All contacts",
    70: "It's me!",
    71: "No contacts",
    72: "No groups",
    73: "No email address",
    74: "Storages",
    75: "All",
    76: "Personal",
    77: "Team",
    78: "Shared with all",
    79: "Groups",
    80: "Share",
    81: "Unshare",
    82: "Send",
    83: "Email to this contact",
    84: "Search messages",
    85: "Edit",
    86: "Delete",
    87: "{contact} will soon appear in {storage} storage",
    88: "Email to the contacts in this group",
    89: "Delete this group",
    90: "Edit group",
    91: "Show additional fields",
    92: "Hide additional fields",
    93: "Home",
    94: "Personal",
    95: "Business",
    96: "Other",
    97: "Group Name",
    98: "Groups",
    99: "Display name",
    100: "Email",
    101: "Personal email",
    102: "Business email",
    103: "Other email",
    104: "Phone",
    105: "Personal Phone",
    106: "Business Phone",
    107: "Mobile",
    108: "Fax",
    109: "Address",
    110: "Personal Address",
    111: "Business Address",
    112: "Skype",
    113: "Facebook",
    114: "Name",
    115: "First name",
    116: "Last name",
    117: "Nickname",
    118: "Street",
    119: "City",
    120: "State/Province",
    121: "Country/Region",
    122: "Zip Code",
    123: "Web Page",
    124: "Company",
    125: "Department",
    126: "Job Title",
    127: "Office",
    128: "Birthday",
    129: "Notes",
    130: "Edit contact",
    131: "Cancel editing contact",
    132: "Save changes",
    133: "Add contact",
    134: "Add group",
    135: "Edit group",
    136: "This group is a Company",
    137: "Cancel editing group",
    138: "Delete contact",
    139: "Are you sure you want to delete {contact}?",
    140: "Delete group",
    141:
        "Are you sure you want to delete {group}? The contacts of this group will not be deleted.",
    142: "Settings",
    143: "Common",
    144: "24 hour format",
    145: "Language",
    146: "System language",
    147: "App theme",
    148: "System theme",
    149: "Dark",
    150: "Light",
    151: "Sync",
    152: "Sync frequency",
    153: "never",
    154: "5 minutes",
    155: "30 minutes",
    156: "1 hour",
    157: "2 hours",
    158: "daily",
    159: "monthly",
    160: "Sync period",
    161: "all time",
    162: "1 month",
    163: "3 months",
    164: "6 months",
    165: "1 year",
    166: "Manage accounts",
    167: "Add new account",
    168: "Relogin to account",
    169: "Delete account",
    170: "Are you sure you want to logout and delete {account}?",
    171: "About",
    172: "Version {version}",
    173: "Terms of Service",
    174: "Privacy policy",
    175: "Login",
    176: "Delete",
    177: "Show email in light theme",
    178: "Cancel",
    179: "Close",
    180: "To spam",
    181: "Save",
    182: "Discard",
    183: "Add account",
    184: "Show all",
    188: "Please enter hostname",
    189: "Please enter email",
    190: "Please enter password",
    191:
        "Could not detect domain from this email, please specify your server URL manually.",
    192: "This user doesn't have mail accounts",
    193: "This account already exists in your accounts list.",
    194: "Please provide recipients",
    195: "Please wait until attachments are uploaded",
    185: "Please specify the name",
    186: "Please specify an email",
    196: "Could not connect to the server",
    187: "You're offline",
    197: "This field is required",
    198: "The email is not valid",
    199: "The name cannot contain \"/\\*?<>|:\"",
    200: "This name already exists",
    201: "Invalid token",
    202: "Invalid email/password",
    203: "Invalid input parameter",
    204: "Database error",
    205: "License problem",
    206: "Demo account",
    207: "Captcha error",
    208: "Access denied",
    209: "Unknown email",
    210: "User is not allowed",
    211: "Such user already exists",
    212: "System is not configured",
    213: "Module not found",
    214: "Method not found",
    215: "License limit",
    216: "Cannot save settings",
    217: "Cannot change password",
    218: "Account's old password is not correct",
    219: "Cannot create contact",
    220: "Cannot create group",
    221: "Cannot update contact",
    222: "Cannot update group",
    223: "Contact data has been modified by another application",
    224: "Cannot get contact",
    225: "Cannot create account",
    226: "Such account already exists",
    227: "Rest other error",
    228: "Rest api disabled",
    229: "Rest unknown method",
    230: "Rest invalid parameters",
    231: "Rest invalid credentials",
    232: "Rest invalid token",
    233: "Rest token expired",
    234: "Rest account lookup failed",
    235: "Rest tenant lookup failed",
    236: "Calendars not allowed",
    237: "Files not allowed",
    238: "Contacts not allowed",
    239: "Helpdesk user already exists",
    240: "Helpdesk system user already exists",
    241: "Cannot create helpdesk user",
    242: "Helpdesk unknown user",
    243: "Helpdesk deactivated user",
    244: "Voice not allowed",
    245: "Incorrect file extension",
    246: "You have reached your cloud storage space limit. Can't upload file.",
    247: "Such file already exists",
    248: "File not found",
    249: "Cannot upload due to file limit",
    250: "Mail server error",
    251: "Unknown error",
    252: "EEE, MMM d, yyyy, HH:mm",
    253: "EEE, MMM d, yyyy 'at' HH:mm",
    254: "MMM d, yyyy",
    255: "Yesterday",
    256:
        "Your account is protected with\nTwo Factor Authentication.\nPlease provide the PIN code.",
    257: "Verification code",
    258: "Verify",
    259: "Invalid code",
    260: "Done",
    261: "Are you sure want to exit?",
    262: "Exit",
    263: "OpenPGP",
    264: "Public keys",
    265: "Private keys",
    266: "Export all public keys",
    267: "Import keys from text",
    268: "Import keys from file",
    303: "Import from text",
    304: "Import from file",
    269: "Generate keys",
    270: "Generate",
    271: "Length",
    272: "Download",
    273: "Share",
    274: "Public key",
    275: "Private key",
    276: "Import keys",
    277: "Import selected keys",
    278: "Check keys",
    279: "Keys not found",
    280: "All public keys",
    281: "Download all",
    282: "Send all",
    283: "Downloading to {path}",
    284: "Are you sure you want to delete OpenPGP key for {user}",
    285: "Sign/Encrypt",
    286: "Open PGP Sign/Encrypt",
    287: "Open PGP Decrypt",
    288: "Sign",
    289: "Encrypt",
    356: "Decrypt",
    290: "invalid password",
    291: "No private key found for {users} user.",
    305: "Undo PGP",
    357: "Message was successfully verified.",
    358: "Message wasn't verified.",
    292: "Message was successfully decrypted and verified.",
    293: "Message was successfully decrypted but wasn't verified.",
    294: "Invalid key or password.",
    295: "Cannot decrypt message.",
    296: "To encrypt your message you need to specify at least one recipient.",
    297: "Verify",
    298: "Keys which are already in the system are greyed out.",
    299: "Find in email",
    306: "Resend",
    307: "Empty Trash",
    308: "Empty Spam",
    309: "Are you sure you want to delete all messages in folder {folder}?",
    310: "Send a self-destructing secure email",
    311: "24 hours",
    312: "72 hours",
    313: "7 days",
    314: "Message lifetime",
    315: "No name",
    316: "Will not sign the data.",
    317: "Will sign the data with your private key.",
    318: "Password-based",
    319: "Key-based",
    320: "The Password-based encryption will be used.",
    321: "The Key-based encryption will be used.",
    322:
        "Selected recipient has PGP public key. The message can be encrypted using this key.",
    323:
        "Selected recipient has no PGP public key. The key-based encryption is not allowed",
    324: "Add digital signature",
    325: "Select recipient",
    326:
        "Hello,\n{sender} user sent you a self-destructing secure email.\nYou can read it using the following link:\n{link}\n{message_password}The message will be accessible for {lifeTime} starting from {now}",
    327: "The message is password-protected. The password is: {password}\n",
    328: "The secure message was shared with you",
    300: "Ok",
    329:
        "The self-descructing secure emails support plain text only. All the formatting will be removed. Also, attachments cannot be encrypted and will be removed from the message.",
    330:
        "The password must be sent using a different channel.\n  Store the password somewhere. You will not be able to recover it otherwise.",
    331: "Self-destructing",
    332: "Password coppied to clipboard",
    333: "Mobile apps are not allowed in your account.",
    334: "Back to login",
    335: "The PGP key will not be valid",
    336: "Re import",
    337: "Delete Key",
    338: "Select key",
    339: "The keys will be imported to contacts",
    340: "For these keys contacts will be created",
    341: "Your keys",
    342: "External public keys",
    343: "Move to: ",
    344: "Move",
    345: "Move to folder",
    346: "Advanced search",
    347: "Advanced search",
    348: "Text",
    349: "Since",
    350: "Till",
    351: "Warning",
    352:
        "You are going to share you private PGP key. The key must be kept from the 3rd parties. Do you want to continue?",
    353: "Import",
    354: "Import contact from vcf?",
    355: "View message headers",
    371: "Forward as attachment",
    372: "No name",
    359: "This user is already logged in",
    360: "Unread",
    361: "Read",
    362: "Show details",
    363: "Hide details",
    364: "Notifications",
    365: "Device identifier",
    366: "Token storing status",
    367: "Resend Push Token",
    368: "Successful",
    369: "Failed",
    373: "Device id copied to clipboard",
    374: "Discard unsaved changes?",
    370: "Contacts imported successfully",
    375: "Encrypt",
    376:
        "If you want messages to this contact to be automatically encrypted and/or signed, check the boxes below. Please note that these messages will be converted to plain text. Attachments will not be encrypted.",
    377: "Delete all",
    378: "Record log in background",
    379: "Show debug view",
    380: "Are you sure you want to delete all logs",
    381: "Counter of uploaded message",
    382: "No PGP public key was found",
    383: "PGP Settings",
    384:
        "The message will be automatically encrypted and/or signed for contacts with OpenPgp keys.\n OpenPGP supports plain text only. All the formatting will be removed before encryption.",
    385: "Not spam",
    386: "password is empty",
    387: "Required password for PGP key",
    392: "Are you sure you want to delete the file",
    389: "Can't connect to the server",
    393: "Invalid security key",
    394: "Two Factor Verification",
    395:
        "This extra step is intended to confirm it’s really you trying to sign in",
    396: "Use security key",
    397: "Please scan your security key or insert it to the device",
    398: "Success",
    399: "Other options",
    400: "Use Backup code",
    401: "Use Authenticator app",
    402: "Use your Security key",
    403: "Security options available",
    404: "Touch you security key",
    405: "Please follow the instructions in the popup dialog",
    406: "There was a problem",
    407:
        "Try using your security key again or try another way to verify it's you",
    408: "Try again",
    409: "Specify verification code from the Authenticator app",
    410: "Invalid backup code",
    411: "Enter one of your 8-character backup codes",
    412: "Backup code",
    413: "You're all set",
    414: "Don't ask again on this device for {daysCount} days",
    415: "Continue",
    416: "Back",
    417: "Message not found",
    390: "Delete cached data and keys",
  };
  String get(int id) => _map[id];
}
