import "s.dart";

class EnS extends S {
  final _map = <int, String>{
    0: "Mail Client",
    1: "Host",
    2: "Email",
    3: "Password",
    4: "Log in to continue",
    5: "No folders",
    6: "Inbox",
    7: "Starred",
    8: "Sent",
    9: "Drafts",
    10: "Spam",
    11: "Trash",
    12: "Reply",
    13: "Reply to all",
    14: "Forward",
    15: "No messages",
    16: "Unread messages:",
    17: "Delete message",
    18: "Delete messages",
    19: "Are you sure you want to delete {subject}?",
    20: "Are you sure you want to delete this message?",
    21: "Are you sure you want to delete these messages?",
    22: "Mail",
    23: "Contacts",
    24: "Settings",
    25: "Log out",
    26: "Search",
    27: "Loading folders...",
    28: "Show details",
    29: "Pictures in this message have been blocked for your safety.",
    30: "Show pictures.",
    31: "Always show pictures in messages from this sender.",
    32: "Attachments",
    33: "Message body",
    34: "To",
    35: "From",
    36: "CC",
    37: "BCC",
    38: "Subject",
    39: "No subject",
    40: "To me",
    41: "No recipients",
    42: "No sender",
    43: "No recipient",
    44: "Sending message...",
    45: "Message saved in drafts",
    46: "No attachments",
    47: "Delete attachment",
    48: "Download attachment",
    49: "Downloading {fileName}...",
    50: "Download failed",
    51: "Cancel download",
    52: "File downloaded into: {path}",
    53: "Upload attachment",
    54: "Uploading {fileName}...",
    55: "Upload failed",
    56: "Cancel upload",
    57: "File uploaded into: {path}",
    58: "Message text...",
    59: "---- Original Message ----",
    60: "From: {emails}",
    61: "To: {emails}",
    62: "CC: {emails}",
    63: "BCC: {emails}",
    64: "Sent: {date}",
    65: "Subject: {subject}",
    66: "On {time}, {from} wrote:",
    67: "Discard changes",
    68: "Would you like to save the changes to drafts?",
    69: "Contacts",
    70: "View group",
    71: "All contacts",
    72: "It's me!",
    73: "No contacts",
    74: "No groups",
    75: "No email address",
    76: "Storages",
    77: "All",
    78: "Personal",
    79: "Team",
    80: "Shared with all",
    81: "Groups",
    82: "Share",
    83: "Unshare",
    84: "Send",
    85: "Email to this contact",
    86: "Search messages",
    87: "Edit",
    88: "Delete",
    89: "{contact} will soon appear in {storage} storage",
    90: "Email to the contacts in this group",
    91: "Delete this group",
    92: "Edit group",
    93: "Show additional fields",
    94: "Hide additional fields",
    95: "Home",
    96: "Personal",
    97: "Business",
    98: "Other",
    99: "Group Name",
    100: "Groups",
    101: "Display name",
    102: "Email",
    103: "Personal email",
    104: "Business email",
    105: "Other email",
    106: "Phone",
    107: "Personal Phone",
    108: "Business Phone",
    109: "Mobile",
    110: "Fax",
    111: "Address",
    112: "Personal Address",
    113: "Business Address",
    114: "Skype",
    115: "Facebook",
    116: "Name",
    117: "First name",
    118: "Last name",
    119: "Nickname",
    120: "Street",
    121: "City",
    122: "State/Province",
    123: "Country/Region",
    124: "Zip Code",
    125: "Web Page",
    126: "Company",
    127: "Department",
    128: "Job Title",
    129: "Office",
    130: "Birthday",
    131: "Notes",
    132: "Edit contact",
    133: "Cancel editing contact",
    134: "Save changes",
    135: "Add contact",
    136: "Add group",
    137: "Edit group",
    138: "This group is a Company",
    139: "Cancel editing group",
    140: "Delete contact",
    141: "Are you sure you want to delete {contact}?",
    142: "Delete group",
    143:
        "Are you sure you want to delete {group}? The contacts of this group will not be deleted.",
    144: "Settings",
    145: "Common",
    146: "24 hour format",
    147: "Language",
    148: "System language",
    149: "App theme",
    150: "System theme",
    151: "Dark",
    152: "Light",
    153: "Sync",
    154: "Sync frequency",
    155: "never",
    156: "5 minutes",
    157: "30 minutes",
    158: "1 hour",
    159: "2 hours",
    160: "daily",
    161: "monthly",
    162: "Sync period",
    163: "all time",
    164: "1 month",
    165: "3 months",
    166: "6 months",
    167: "1 year",
    168: "Manage accounts",
    169: "Add new account",
    170: "Relogin to account",
    171: "Delete account",
    172: "Are you sure you want to logout and delete {account}?",
    173: "About",
    174: "Version {version}",
    175: "Terms of Service",
    176: "Privacy policy",
    177: "Login",
    178: "Delete",
    179: "Show email in light theme",
    180: "Cancel",
    181: "Close",
    182: "To spam",
    183: "Save",
    184: "Discard",
    185: "Add account",
    186: "Show all",
    187: "Please enter hostname",
    188: "Please enter email",
    189: "Please enter password",
    190:
        "Could not detect domain from this email, please specify your server URL manually.",
    191: "This user doesn't have mail accounts",
    192: "This account already exists in your accounts list.",
    193: "Please provide recipients",
    194: "Please wait until attachments are uploaded",
    195: "Please specify the name",
    196: "Please specify an email",
    197: "Could not connect to the server",
    198: "You're offline",
    199: "This field is required",
    200: "The email is not valid",
    201: "The name cannot contain \"/\\*?<>|:\"",
    202: "This name already exists",
    203: "Invalid token",
    204: "Invalid email/password",
    205: "Invalid input parameter",
    206: "Database error",
    207: "License problem",
    208: "Demo account",
    209: "Captcha error",
    210: "Access denied",
    211: "Unknown email",
    212: "User is not allowed",
    213: "Such user already exists",
    214: "System is not configured",
    215: "Module not found",
    216: "Method not found",
    217: "License limit",
    218: "Cannot save settings",
    219: "Cannot change password",
    220: "Account's old password is not correct",
    221: "Cannot create contact",
    222: "Cannot create group",
    223: "Cannot update contact",
    224: "Cannot update group",
    225: "Contact data has been modified by another application",
    226: "Cannot get contact",
    227: "Cannot create account",
    228: "Such account already exists",
    229: "Rest other error",
    230: "Rest api disabled",
    231: "Rest unknown method",
    232: "Rest invalid parameters",
    233: "Rest invalid credentials",
    234: "Rest invalid token",
    235: "Rest token expired",
    236: "Rest account lookup failed",
    237: "Rest tenant lookup failed",
    238: "Calendars not allowed",
    239: "Files not allowed",
    240: "Contacts not allowed",
    241: "Helpdesk user already exists",
    242: "Helpdesk system user already exists",
    243: "Cannot create helpdesk user",
    244: "Helpdesk unknown user",
    245: "Helpdesk deactivated user",
    246: "Voice not allowed",
    247: "Incorrect file extension",
    248: "You have reached your cloud storage space limit. Can't upload file.",
    249: "Such file already exists",
    250: "File not found",
    251: "Cannot upload due to file limit",
    252: "Mail server error",
    253: "Unknown error",
    254: "EEE, MMM d, yyyy, HH:mm",
    255: "EEE, MMM d, yyyy 'at' HH:mm",
    256: "MMM d, yyyy",
    257: "Yesterday",
    258:
        "Your account is protected with\nTwo Factor Authentication.\nPlease provide the PIN code.",
    259: "Verification code",
    260: "Verify",
    261: "Invalid code",
    262: "Done",
    263: "Are you sure want to exit",
    264: "Exit",
    265: "OpenPGP",
    266: "Public keys",
    267: "Private keys",
    268: "Export all public keys",
    269: "Import keys from text",
    270: "Import keys from file",
    271: "Import from text",
    272: "Import from file",
    273: "Generate keys",
    274: "Generate",
    275: "Length",
    276: "Download",
    277: "Share",
    278: "Public key",
    279: "Private key",
    280: "Import keys",
    281: "Import selected keys",
    282: "Check keys",
    283: "Keys not found",
    284: "All public keys",
    285: "Download all",
    286: "Send all",
    287: "Downloading to {path}",
    288: "Are you sure you want to delete OpenPGP key for {user}",
    289: "Sign/Encrypt",
    290: "Open PGP Sign/Encrypt",
    291: "Open PGP Decrypt",
    292: "Sign",
    293: "Encrypt",
    294: "Decrypt",
    295: "invalid password",
    296: "No private key found for {users} user.",
    297: "Undo PGP",
    298: "Message was successfully verified.",
    299: "Message wasn't verified.",
    300: "Message was successfully decrypted and verified.",
    301: "Message was successfully decrypted but wasn't verified.",
    302: "Invalid key or password.",
    303: "Cannot decrypt message.",
    304: "To encrypt your message you need to specify at least one recipient.",
    305: "Verify",
    306: "Keys which are already in the system are greyed out.",
    307: "Find in email",
    308: "Resend",
    309: "Empty Trash",
    310: "Empty Spam",
    311: "Are you sure you want to delete all messages in folder {folder}?",
    312: "Send a self-destructing secure email",
    313: "24 hours",
    314: "72 hours",
    315: "7 days",
    316: "Message lifetime",
    317: "No name",
    318: "Will not sign the data.",
    319: "Will sign the data with your private key.",
    320: "Password-based",
    321: "Key-based",
    322: "The Password-based encryption will be used.",
    323: "The Key-based encryption will be used.",
    324:
        "Selected recipient has PGP public key. The message can be encrypted using this key.",
    325:
        "Selected recipient has no PGP public key. The key-based encryption is not allowed",
    326: "Add digital signature",
    327: "Select recipient",
    328:
        "Hello,\n{sender} user sent you a self-destructing secure email.\nYou can read it using the following link:\n{link}\n{message_password}The message will be accessible for {lifeTime} starting from {now}",
    329: "The message is password-protected. The password is: {password}\n",
    330: "The secure message was shared with you",
    331: "Ok",
    332:
        "The self-descructing secure emails support plain text only. All the formatting will be removed. Also, attachments cannot be encrypted and will be removed from the message.",
    333:
        "The password must be sent using a different channel.\n  Store the password somewhere. You will not be able to recover it otherwise.",
    334: "Self-destructing",
    335: "Password coppied to clipboard",
    336: "Mobile apps are not allowed in your account.",
    337: "Back to login",
    338: "The PGP key will not be valid",
    339: "Re import",
    340: "Delete Key",
    341: "Select key",
    342: "The keys will be imported to contacts",
    343: "For these keys contacts will be created",
    344: "Your keys",
    345: "External public keys",
    346: "Move to: ",
    347: "Move",
    348: "Move to folder",
    349: "Advanced search",
    350: "Advanced search",
    351: "Text",
    352: "Since",
    353: "Till",
    354: "Warning",
    355:
        "You are going to share you private PGP key. The key must be kept from the 3rd parties. Do you want to continue?",
    356: "Import",
    357: "Import contact from vcf?",
    358: "View message headers",
    359: "Forward as attachment",
    360: "No name",
    361: "This user is already logged in",
    362: "Unread",
    363: "Read",
    364: "Show details",
    365: "Hide details",
    366: "Notifications",
    367: "Device identifier",
    368: "Token storing status",
    369: "Resend Push Token",
    370: "Successful",
    371: "Failed",
    372: "Device id copied to clipboard",
    373: "Discard unsaved changes?",
    374: "Contacts imported successfully",
    375: "Encrypt",
    376:
        "If you want messages to this contact to be automatically encrypted and/or signed, check the boxes below. Please note that these messages will be converted to plain text. Attachments will not be encrypted.",
    377: "Delete all",
    378: "Record log in background",
    379: "Show debug view",
    380: "Are you sure you want to delete all logs",
    381: "Counter of uploaded message",
    382: "No PGP public key was found",
    383: "PGP Settings",
    384:
        "The message will be automatically encrypted and/or signed for contacts with OpenPgp keys.\n OpenPGP supports plain text only. All the formatting will be removed before encryption.",
    385: "Not spam",
    386: "password is empty",
    387: "Required password for PGP key",
    388: "Are you sure you want to delete file {name}",
    389: "Can't connect to the server",
    390: "Invalid security key",
    391: "Two Factor Verification",
    392:
        "This extra step is intended to confirm it’s really you trying to sign in",
    393: "Use security key",
    394: "Please scan your security key or insert it to the device",
    395: "Success",
    396: "Other options",
    397: "Use Backup code",
    398: "Use Authenticator app",
    399: "Use your Security key",
    400: "Security options available",
    401: "Touch you security key",
    402: "Please follow the instructions in the popup dialog",
    403: "There was a problem",
    404:
        "Try using your security key again or try another way to verify it's you",
    405: "Try again",
    406: "Specify verification code from the Authenticator app",
    407: "Invalid backup code",
    408: "Enter one of your 8-character backup codes",
    409: "Backup code",
    410: "You're all set",
    411: "Don't ask again on this device for 30 days",
    412: "Continue",
  };
  String get(int id) => _map[id];
}
