import "s.dart";

class RuS extends S {
  final _map = <int, String>{
    S.app_title: "Mail Client",
    S.login_input_host: "Домен",
    S.login_input_email: "Почта",
    S.login_input_password: "Пароль",
    S.login_to_continue: "Войдите в аккаунт",
    S.folders_empty: "Нет папок",
    S.folders_inbox: "Входящие",
    S.folders_starred: "Отмеченные",
    S.folders_sent: "Отправленные",
    S.folders_drafts: "Черновики",
    S.folders_spam: "Спам",
    S.folders_trash: "Корзина",
    S.messages_reply: "Ответить",
    S.messages_reply_all: "Ответить всем",
    S.messages_forward: "Переслать",
    S.messages_empty: "Нет сообщений",
    S.messages_filter_unread: "Непрочитаные сообщения:",
    S.messages_delete_title: "Удалить сообщение",
    S.messages_delete_title_with_count: "Удалить сообщения",
    S.messages_delete_desc_with_subject:
        "Вы уверены, что хотите удалить {subject}?",
    S.messages_delete_desc: "Вы уверены, что хотите удалить это сообщение?",
    S.messages_delete_desc_with_count:
        "Вы уверены, что хотите удалить эти сообщения?",
    S.messages_list_app_bar_mail: "Почта",
    S.messages_list_app_bar_contacts: "Контакты",
    S.messages_list_app_bar_settings: "Настройки",
    S.messages_list_app_bar_logout: "Выйти",
    S.messages_list_app_bar_search: "Поиск",
    S.messages_list_app_bar_loading_folders: "Загрузка папок...",
    S.messages_show_details: "Показать детали",
    S.messages_images_security_alert:
        "Из соображений безобазности картинки были заблокированы.",
    S.messages_show_images: "Показать изображения.",
    S.messages_always_show_images:
        "Всегда показывать изображения в сообщениях от данного отправителя.",
    S.messages_view_tab_attachments: "Вложения",
    S.messages_view_tab_message_body: "Тело письма",
    S.messages_to: "Кому",
    S.messages_from: "От кого",
    S.messages_cc: "Копия",
    S.messages_bcc: "Скрытая копия",
    S.messages_subject: "Тема",
    S.messages_no_subject: "Без темы",
    S.messages_to_me: "Мне",
    S.messages_no_receivers: "Нет получателей",
    S.messages_unknown_sender: "Нет отправителя",
    S.messages_unknown_recipient: "Нет получателя",
    S.messages_sending: "Отправка сообщения...",
    S.messages_saved_in_drafts: "Сообщение сохранено в черновиках",
    S.messages_attachments_empty: "Нет вложений",
    S.messages_attachment_delete: "Удалить файл",
    S.messages_attachment_download: "Скачать файл",
    S.messages_attachment_downloading: "Загрузка {fileName}...",
    S.messages_attachment_download_failed: "Ошибка загрузки",
    S.messages_attachment_download_cancel: "Отменить загрузку",
    S.messages_attachment_download_success: "Файл загружен в: {path}",
    S.messages_attachment_upload: "Загрузить файл",
    S.messages_attachment_uploading: "Загрузка {fileName}...",
    S.messages_attachment_upload_failed: "Загрузка не удалась",
    S.messages_attachment_upload_cancel: "Отменить загрузку",
    S.messages_attachment_upload_success: "Файл загружен в: {path}",
    S.compose_body_placeholder: "Текст сообщения...",
    S.compose_forward_body_original_message: "---- Оригинал сообщения ----",
    S.compose_forward_from: "От: {emails}",
    S.compose_forward_to: "Кому: {emails}",
    S.compose_forward_cc: "Копия: {emails}",
    S.compose_forward_bcc: "Скрытая копия: {emails}",
    S.compose_forward_sent: "Отправлено: {date}",
    S.compose_forward_subject: "Тема: {subject}",
    S.compose_reply_body_title: "В {time}, {from} написал(а):",
    S.compose_discard_save_dialog_title: "Сбросить изменения",
    S.compose_discard_save_dialog_description:
        "Сохранить изменения в черновиках?",
    S.contacts: "Контакты",
    S.contacts_list_app_bar_view_group: "Инфорамация о группе",
    S.contacts_list_app_bar_all_contacts: "Все контакты",
    S.contacts_list_its_me_flag: "Это я!",
    S.contacts_empty: "Контактов нет",
    S.contacts_groups_empty: "Групп нет",
    S.contacts_email_empty: "Нет эл. почты",
    S.contacts_drawer_section_storages: "Хранилища",
    S.contacts_drawer_storage_all: "Все",
    S.contacts_drawer_storage_personal: "Личные",
    S.contacts_drawer_storage_team: "Коллеги",
    S.contacts_drawer_storage_shared: "Доступные всем",
    S.contacts_drawer_section_groups: "Группы",
    S.contacts_view_app_bar_share: "Сделать общим",
    S.contacts_view_app_bar_unshare: "Сделать личным",
    S.contacts_view_app_bar_attach: "Переслать",
    S.contacts_view_app_bar_send_message: "Написать",
    S.contacts_view_app_bar_search_messages: "Найти сообщения",
    S.contacts_view_app_bar_edit_contact: "Редактировать",
    S.contacts_view_app_bar_delete_contact: "Удалить",
    S.contacts_shared_message: "{contact} скоро появится в хранилище {storage}",
    S.contacts_group_view_app_bar_send_message:
        "Отправить сообщение контактам в этой группе",
    S.contacts_group_view_app_bar_delete: "Удалить группу",
    S.contacts_group_view_app_bar_edit: "Редактировать группу",
    S.contacts_view_show_additional_fields: "Показать дополнительные поля",
    S.contacts_view_hide_additional_fields: "Скрыть дополнительные поля",
    S.contacts_view_section_home: "Дом",
    S.contacts_view_section_personal: "Личное",
    S.contacts_view_section_business: "Бизнес",
    S.contacts_view_section_other_info: "Прочее",
    S.contacts_view_section_group_name: "Имя группы",
    S.contacts_view_section_groups: "Группы",
    S.contacts_view_display_name: "Отображаемое имя",
    S.contacts_view_email: "Эл. почта",
    S.contacts_view_personal_email: "Домашняя эл. почта",
    S.contacts_view_business_email: "Рабочая эл. почта",
    S.contacts_view_other_email: "Дополнительная эл. почта",
    S.contacts_view_phone: "Телефон",
    S.contacts_view_personal_phone: "Личный телефон",
    S.contacts_view_business_phone: "Рабочий телефон",
    S.contacts_view_mobile: "Мобильный",
    S.contacts_view_fax: "Факс",
    S.contacts_view_address: "Адрес",
    S.contacts_view_personal_address: "Домашний адрес",
    S.contacts_view_business_address: "Рабочий адрес",
    S.contacts_view_skype: "Skype",
    S.contacts_view_facebook: "Facebook",
    S.contacts_view_name: "Имя",
    S.contacts_view_first_name: "Имя",
    S.contacts_view_last_name: "Фамилия",
    S.contacts_view_nickname: "Ник",
    S.contacts_view_street_address: "Улица",
    S.contacts_view_city: "Город",
    S.contacts_view_province: "Регион",
    S.contacts_view_country: "Страна",
    S.contacts_view_zip: "Индекс",
    S.contacts_view_web_page: "Веб сайт",
    S.contacts_view_company: "Компания",
    S.contacts_view_department: "Отдел",
    S.contacts_view_job_title: "Должность",
    S.contacts_view_office: "Офис",
    S.contacts_view_birthday: "День рождения",
    S.contacts_view_notes: "Заметки",
    S.contacts_edit: "Редактировать контакт",
    S.contacts_edit_cancel: "Отменить редактирование контакта",
    S.contacts_edit_save: "Сохранить",
    S.contacts_add: "Добавить контакт",
    S.contacts_group_add: "Добавить группу",
    S.contacts_group_edit: "Редактировать группу",
    S.contacts_group_edit_is_organization: "Эта группа является компанией",
    S.contacts_group_edit_cancel: "Отменить редактирование группы",
    S.contacts_delete_title: "Удалить контакт",
    S.contacts_delete_desc_with_name:
        "Вы действительно хотите удалить {contact}?",
    S.contacts_group_delete_title: "Удалить группу",
    S.contacts_group_delete_desc_with_name:
        "Вы действительно хотите удалить {group}? Контакты этой группы удалены не будут.",
    S.settings: "Настройки",
    S.settings_common: "Общие",
    S.settings_24_time_format: "24 часовой формат времени",
    S.settings_language: "Язык",
    S.settings_language_system: "Язык системы",
    S.settings_dark_theme: "Тема",
    S.settings_dark_theme_system: "Системная",
    S.settings_dark_theme_dark: "Тёмная",
    S.settings_dark_theme_light: "Светлая",
    S.settings_sync: "Синхронизация",
    S.settings_sync_frequency: "Обновлять каждые",
    S.settings_sync_frequency_never: "отключено",
    S.settings_sync_frequency_minutes5: "5 минут",
    S.settings_sync_frequency_minutes30: "30 минут",
    S.settings_sync_frequency_hours1: "1 час",
    S.settings_sync_frequency_hours2: "два часа",
    S.settings_sync_frequency_daily: "ежедневно",
    S.settings_sync_frequency_monthly: "ежемесячно",
    S.settings_sync_period: "Синхронизировать письма за",
    S.settings_sync_period_all_time: "все время",
    S.settings_sync_period_months1: "1 месяц",
    S.settings_sync_period_months3: "3 месяца",
    S.settings_sync_period_months6: "6 месяцев",
    S.settings_sync_period_years1: "1 год",
    S.settings_accounts_manage: "Управление аккаунтами",
    S.settings_accounts_add: "Добавить новый аккаунт",
    S.settings_accounts_relogin: "Войти в аккаунт",
    S.settings_accounts_delete: "Удалить аккаунт",
    S.settings_accounts_delete_description:
        "Вы действительно хотите выйти из аккаунта {account} и удалить его?",
    S.settings_about: "О приложении",
    S.settings_about_app_version: "Версия {version}",
    S.settings_about_terms_of_service: "Правила пользования",
    S.settings_about_privacy_policy: "Политика конфиденциальности",
    S.btn_login: "Войти",
    S.btn_delete: "Удалить",
    S.btn_show_email_in_light_theme: "Показать светлый вариант письма",
    S.btn_cancel: "Отмена",
    S.btn_close: "Закрыть",
    S.btn_to_spam: "Спам",
    S.btn_save: "Сохранить",
    S.btn_discard: "Сбросить",
    S.btn_add_account: "Добавить аккаунт",
    S.btn_show_all: "Показать все",
    S.error_login_input_hostname: "Введите домен",
    S.error_login_input_email: "Введите эл. почту",
    S.error_login_input_password: "Введите пароль",
    S.error_login_auto_discover:
        "Не удалось определить домен автоматически, пожалуйста, укажите его вручную.",
    S.error_login_no_accounts: "У данного пользователя нет почтовых аккаунтов",
    S.error_login_account_exists:
        "Этот аккаунт уже находится в списке ваших аккаунтов.",
    S.error_compose_no_receivers: "Укажите получателей",
    S.error_compose_wait_attachments:
        "Пожалуйста подождите пока загрузятся вложения",
    S.error_contacts_save_name_empty: "Укажите имя",
    S.error_contacts_email_empty: "Укажите эл. почту",
    S.error_input_validation_empty: "Это поле обязательно",
    S.error_connection_offline: "Отсутствует подключение к инетернету",
    S.error_server_invalid_token: "Неверный токен",
    S.error_server_auth_error: "Неверный адрес электронной почты / пароль",
    S.error_server_invalid_input_parameter: "Неверный входной параметр",
    S.error_server_data_base_error: "Ошибка базы данных",
    S.error_server_license_problem: "Проблема с лицензией",
    S.error_server_demo_account: "Демо аккаунт",
    S.error_server_captcha_error: "Ошибка Captcha",
    S.error_server_access_denied: "Доступ запрещён",
    S.error_server_unknown_email: "Неизвестный адрес электронной почты",
    S.error_server_user_not_allowed: "Пользователь не допущен",
    S.error_server_user_already_exists: "Такой пользователь уже существует",
    S.error_server_system_not_configured: "Система не настроена",
    S.error_server_module_not_found: "Модуль не найден",
    S.error_server_method_not_found: "Метод не найден",
    S.error_server_license_limit: "Лимит лицензии",
    S.error_server_can_not_save_settings: "Не удалось сохранить настройки",
    S.error_server_can_not_change_password: "Не удалось сменить пароль",
    S.error_server_account_old_password_not_correct:
        "Неправильный старый пароль учетной записи",
    S.error_server_can_not_create_contact: "Не удалось создать контакт",
    S.error_server_can_not_create_group: "Не удалось создать группу",
    S.error_server_can_not_update_contact: "Не удается обновить контакт",
    S.error_server_can_not_update_group: "Не удается обновить группу",
    S.error_server_contact_data_has_been_modified_by_another_application:
        "Контактные данные были изменены другим приложением",
    S.error_server_can_not_get_contact: "Не удалось получить контакт",
    S.error_server_can_not_create_account: "Не могу создать аккаунт",
    S.error_server_account_exists: "Такой аккаунт уже существует",
    S.error_server_rest_other_error: "Другая ошибка REST",
    S.error_server_rest_api_disabled: "Остальные API отключены",
    S.error_server_rest_unknown_method: "Неизвестный метод REST",
    S.error_server_rest_invalid_parameters: "Неверные параметры REST",
    S.error_server_rest_invalid_credentials: "Неверные учетные данные REST",
    S.error_server_rest_invalid_token: "Недействительный токен REST",
    S.error_server_rest_token_expired: "Срок действия токена REST истек",
    S.error_server_rest_account_find_failed: "Не удалось найти аккаунт REST",
    S.error_server_rest_tenant_find_failed: "Не удалось найти тенант REST",
    S.error_server_calendars_not_allowed: "Календари не разрешены",
    S.error_server_files_not_allowed: "Файлы не разрешены",
    S.error_server_contacts_not_allowed: "Контакты не разрешены",
    S.error_server_helpdesk_user_already_exists:
        "Пользователь службы поддержки уже существует",
    S.error_server_helpdesk_system_user_exists:
        "Пользователь системы службы поддержки уже существует",
    S.error_server_can_not_create_helpdesk_user:
        "Невозможно создать пользователя службы поддержки",
    S.error_server_helpdesk_unknown_user:
        "Служба поддержки неизвестного пользователя",
    S.error_server_helpdesk_unactivated_user:
        "Неактивированный пользователь службы поддержки",
    S.error_server_voice_not_allowed: "Голос не разрешен",
    S.error_server_incorrect_file_extension: "Неверное расширение файла",
    S.error_server_can_not_upload_file_quota:
        "Вы достигли лимита места в облачном хранилище. Не могу загрузить файл.",
    S.error_server_file_already_exists: "Такой файл уже существует",
    S.error_server_file_not_found: "Файл не найден",
    S.error_server_can_not_upload_file_limit: "Превышен лимит загрузки файлов",
    S.error_server_mail_server_error: "Ошибка почтового сервера",
    S.error_unknown: "Неизвестная ошибка",
    S.format_compose_forward_date: "EEE, d MMM, yyyy, HH:mm",
    S.format_compose_reply_date: "EEE, d MMM, yyyy 'at' HH:mm",
    S.format_contacts_birth_date: "d MMM, yyyy",
    S.label_message_yesterday: "Вчера",
    S.hint_2fa:
        "Ваш аккаунт защищён\nдвухфакторной аутентификацией.\nУкажите PIN код.",
    S.label_pgp_settings: "OpenPGP",
    S.label_pgp_public_keys: "Public keys",
    S.label_pgp_private_keys: "Private keys",
    S.btn_pgp_export_all_public_keys: "Экспортировать все публичные ключи",
    S.btn_pgp_import_keys_from_text: "Импортировать ключ из текста",
    S.btn_pgp_import_keys_from_file: "Импортировать ключ из файла",
    S.btn_pgp_generate_keys: "Создать ключи",
    S.btn_pgp_generate: "Создать",
    S.label_length: "Длина",
    S.btn_download: "Скачать",
    S.btn_share: "Поделиться",
    S.label_pgp_public_key: "Public key",
    S.label_pgp_private_key: "Private key",
    S.label_pgp_import_key: "Импорт ключей",
    S.btn_pgp_import_selected_key: "Импортировать выбранные",
    S.btn_pgp_check_keys: "Проверить ключи",
    S.error_pgp_keys_not_found: "Ключи не найдены",
    S.label_pgp_all_public_key: "Все публичные ключи",
    S.btn_pgp_download_all: "Скачать всё",
    S.btn_php_send_all: "Отправить всё",
    S.label_pgp_downloading_to: "Загруженно в {path}",
    S.hint_pgp_delete_user_key_confirm:
        "Вы действительно хотите удалить OpenPGP key для {user}?",
    S.btn_pgp_sign_or_encrypt: "Sign/Encrypt",
    S.label_pgp_sign_or_encrypt: "Open PGP шифрование",
    S.label_pgp_decrypt: "Open PGP дешифровка",
    S.label_pgp_sign: "Подписать",
    S.btn_pgp_encrypt: "Зашифровать",
    S.btn_pgp_decrypt: "Дешифровать",
    S.error_pgp_invalid_password: "Неверный пароль",
    S.error_pgp_not_found_keys_for: "Ключи для пользователя {users} не найдены",
    S.btn_pgp_undo_pgp: "Отменить PGP",
    S.label_pgp_verified: "Сообщение успешно проверено.",
    S.label_pgp_not_verified: "Сообщение не проверено.",
    S.label_pgp_decrypted_and_verified:
        "Сообщение успешно дешифровано и проверено.",
    S.label_pgp_decrypted_but_not_verified:
        "Сообщение успешно дешифровано, но не проверено.",
    S.error_pgp_invalid_key_or_password: "Неверный ключ либо пароль.",
    S.error_pgp_can_not_decrypt: "Не удалось дешифровать.",
    S.error_pgp_need_contact_for_encrypt:
        "Чтобы зашифровать сообщение нужно указать хотя бы одного получателя.",
    S.button_pgp_verify_sign: "Проверить",
    S.hint_pgp_already_have_keys:
        "Ключи, которые уже есть в системе, выделены серым цветом.",
    S.error_connection: "Не удалось установить соединение с сервером",
    S.error_input_validation_email: "Неверный email",
    S.error_input_validation_name_illegal_symbol:
        "Имя не может содержать \"/\\*?<>|:\"",
    S.error_input_validation_unique_name: "Такое имя уже записано",
    S.input_2fa_pin: "PIN",
    S.btn_verify_pin: "Подтвердите PIN",
    S.error_invalid_pin: "Неверный PIN",
    S.btn_done: "Готово",
    S.hint_confirm_exit: "Вы уверены что хотите выйти?",
    S.btn_exit: "Выйти",
    S.btn_contact_find_in_email: "Искать в письмах",
    S.btn_message_resend: "Повторить",
    S.btn_message_empty_trash_folder: "Очистить Корзину",
    S.btn_message_empty_spam_folder: "Очистить Спам",
    S.hint_message_empty_folder:
        "Вы уверены, что хотите удалить все сообщение в папке {folder}?",
    S.label_self_destructing: "Send a self-destructing secure email",
    S.self_destructing_life_time_day: "24 hours",
    S.self_destructing_life_time_days_3: "72 hours",
    S.self_destructing_life_time_days_7: "7 days",
    S.message_lifetime: "Message lifetime",
    S.label_pgp_key_with_not_name: "Без имени",
    S.error_pgp_select_recipient: "Выберите получателя",
    S.btn_ok: "Ок",
    S.label_self_destructing_not_sign_data: "Will not sign the data.",
    S.label_self_destructing_sign_data:
        "Will sign the data with your private key.",
    S.input_self_destructing_password_based_encryption: "Password-based",
    S.input_self_destructing_key_based_encryption: "Key-based",
    S.label_self_destructing_password_based_encryption_used:
        "The Password-based encryption will be used.",
    S.label_self_destructing_key_based_encryption_used:
        "The Key-based encryption will be used.",
    S.hint_self_destructing_encrypt_with_key:
        "Selected recipient has PGP public key. The message can be encrypted using this key.",
    S.hint_self_destructing_encrypt_with_not_key:
        "Selected recipient has no PGP public key. The key-based encryption is not allowed",
    S.input_self_destructing_add_digital_signature: "Add digital signature",
    S.template_self_destructing_message:
        "Hello,\n{sender} user sent you a self-destructing secure email.\nYou can read it by the following link:\n{link}\n{message_password}The message will be accessible for {lifeTime} starting from {now}",
    S.template_self_destructing_message_password:
        "The message is password-protected. The password is: {password}\n",
    S.template_self_destructing_message_title:
        "The secure message was shared with you",
    S.hint_self_destructing_supports_plain_text_only:
        "The self-descructing secure emails support plain text only. All the formatting will be removed. Also, attachments cannot be encrypted and will be removed from the message.",
    S.hint_self_destructing_sent_password_using_different_channel:
        "The password must be sent using a different channel.\n  Store the password somewhere. You will not be able to recover it otherwise.",
    S.btn_self_destructing: "Self-destructing",
    S.hint_self_destructing_password_coppied_to_clipboard: "Пароль скопирован",
    S.btn_pgp_import_from_text: "Импортировать из текста",
    S.btn_pgp_import_from_file: "Импортировать из файла",
    S.hint_login_upgrade_your_plan:
        "Mobile apps are not allowed in your account.",
    S.btn_login_back_to_login: "Back to login",
    S.error_contact_pgp_key_will_not_be_valid:
        "Pgp ключ не будет действительным",
    S.btn_contact_key_re_import: "Импортировать заново",
    S.btn_contact_delete_key: "Удалить ключ",
    S.label_contact_select_key: "Выберите ключ",
    S.hint_pgp_keys_will_be_import_to_contacts:
        "Эти ключи будут экспортированны в контакты",
    S.hint_pgp_keys_contacts_will_be_created:
        "Для этих ключей будут созданны контакты",
    S.hint_pgp_your_keys: "Ваши ключи",
    S.label_pgp_contact_public_keys: "Публичные ключи контактов",
    S.label_message_move_to: "Переместить в: ",
    S.btn_message_move: "Move",
    S.label_message_move_to_folder: "Переместить в папку",
    S.btn_message_advanced_search: "Расширенный поиск",
    S.input_message_search_text: "Текст",
    S.input_message_search_since: "От",
    S.input_message_search_till: "До",
    S.label_pgp_share_warning: "Предупреждение",
    S.hint_pgp_share_warning:
        "Вы собираетесь поделиться своим закрытым PGP-ключом. Закрытый ключ должен храниться только у владельца. Продолжить?",
    S.label_message_headers: "Заголовки письма",
    S.label_message_advanced_search: "Advanced search",
    S.btn_vcf_import: "Import",
    S.hint_vcf_import: "Import contact from vcf?",
    S.error_user_already_logged: "Это пользователь уже авторизирован",
    S.btn_unread: "Unread",
    S.btn_read: "Read",
    S.btn_show_details: "Show details",
    S.btn_hide_details: "Hide details",
    S.label_notifications_settings: "Notifications",
    S.label_device_identifier: "Device identifier",
    S.label_token_storing_status: "Token storing status",
    S.btn_resend_push_token: "Resend Push Token",
    S.label_token_successful: "Successful",
    S.label_token_failed: "Failed",
    S.label_contacts_were_imported_successfully:
        "Contacts imported successfully",
    S.label_forward_as_attachment: "Forward as attachment",
    S.label_contact_with_not_name: "No name",
    S.label_device_id_copied_to_clip_board: "Device id copied to clipboard",
    S.label_discard_not_saved_changes: "Discard not saved changes?",
    S.label_pgp_encrypt: "Encrypt",
    S.hint_auto_encrypt_messages:
        "If you want messages to this contact to be automatically encrypted and/or signed, check the boxes below. Please note that these messages will be converted to plain text. Attachments will not be encrypted.",
    S.btn_log_delete_all: "Delete all",
    S.label_record_log_in_background: "Record log in background",
    S.label_show_debug_view: "Show debug view",
    S.hint_log_delete_all: "Are you sure you want to delete all logs",
    S.label_enable_uploaded_message_counter: "Counter of uploaded message",
    S.error_no_pgp_key: "No PGP public key was found",
    S.label_contact_pgp_settings: "PGP Settings",
    S.hint_pgp_message_automatically_encrypt:
        "The message will be automatically encrypted and/or signed for contacts with OpenPgp keys.\n OpenPGP supports plain text only. All the formatting will be removed before encryption.",
    S.btn_not_spam: "Not spam",
    S.error_password_is_empty: "password is empty",
    S.label_encryption_password_for_pgp_key: "Required password for PGP key",
    S.hint_log_delete_record: "Are you sure you want to delete file {name}",
    S.error_timeout: "Can't connect to the server",
    S.clear_cache_during_logout: "Очистить локальный кэш и сохранённые ключи",
    S.no_permission_to_local_storage:
        "Нет разрешения для доступа к файлам. Проверьте настройки на вашем устройстве.",
    S.already_have_key: "У вас уже есть открытый или закрытый ключ",
  };
  String get(int id) => _map[id];
}
