import "s.dart";

class TrS extends S {
  final _map = <int, String>{
    0: "E-posta Okuyucu",
    1: "Sunucu",
    2: "E-posta",
    3: "Şifre",
    4: "Devam etmek için giriş yapın",
    5: "Klasör yok",
    6: "Gelen Kutusu",
    7: "Yıldızlı",
    8: "Gönderilen",
    9: "Taslaklar",
    10: "Spam",
    11: "Çöp Kutusu",
    12: "Yanıtla",
    13: "Tümünü yanıtla",
    14: "Yönlendir",
    15: "İleti yok",
    16: "Okunmamış iletiler:",
    17: "İletiyi sil",
    19: "{subject} silmek istediğinize emin misiniz?",
    20: "Bu iletiyi silmek istediğinden emin misin?",
    390: "E-posta",
    23: "Kişiler",
    24: "Ayarlar",
    25: "Oturumu kapat",
    26: "Ara",
    27: "Klasörler yükleniyor...",
    28: "Detayları göster",
    29: "Bu iletideki görseller güvenliğiniz sebebiyle engellendi. ",
    30: "Görselleri göster.",
    31: "Görselleri her zaman göster.",
    32: "Ekler",
    33: "İleti metni",
    34: "Alıcı",
    35: "Gönderen",
    36: "CC",
    37: "BCC",
    38: "Konu",
    39: "Konu yok",
    40: "Bana",
    41: "Alıcı yok",
    42: "Gönderen yok",
    43: "Alıcı yok",
    44: "İleti gönderiliyor...",
    45: "İleti taslaklara kaydedildi",
    46: "Ek yok",
    47: "Eki sil",
    48: "Eki indir",
    49: "{fileName} indiriliyor ...",
    50: "İndirme işlemi başarısız",
    51: "İndirmeyi iptal et",
    52: "Dosya şuraya indirildi: {path}",
    53: "Dosya yükle",
    54: "{fileName} yükleniyor ...",
    55: "Yükleme işlemi başarısız",
    56: "Yüklemeyi iptal et",
    57: "Dosya şuraya yüklendi: {path}",
    58: "İleti metni...",
    59: "---- Orijinal İleti ----",
    60: "Gönderen: {emails}",
    61: "Alıcı: {emails}",
    62: "CC: {emails}",
    63: "BCC: {emails}",
    64: "Gönderildi: {date}",
    65: "Konu: {subject}",
    66: "{time},tarihinde {from} yazdı:",
    67: "Değişiklikleri iptal et",
    68: "Değişiklikleri taslak olarak kaydetmek ister misiniz?",
    69: "Kişiler",
    70: "Grubu görüntüle",
    71: "Tüm kişiler",
    72: "Sizin hesabınız",
    73: "Kişi yok",
    74: "Grup yok",
    75: "E-posta adresi yok",
    76: "Depolama",
    77: "Tümü",
    78: "Kişisel",
    79: "Ekip",
    80: "Herkesle paylaşıldı",
    81: "Gruplar",
    82: "Paylaş",
    83: "Paylaşma",
    84: "Gönder",
    85: "Bu kişiye e-posta gönder",
    86: "İletilerde ara",
    87: "Düzenle",
    88: "Sil",
    89: "{contact} kişisi birazdan {storage} alanında görünür olacak. ",
    90: "Gruptaki kişilere e-posta gönder",
    91: "Bu grubu sil",
    92: "Grubu güncelle",
    93: "Ek alanları göster",
    94: "Ek alanları gizle",
    95: "Ana Sayfa",
    96: "Kişisel",
    97: "Şirket",
    98: "Diğer",
    99: "Grup Adı",
    100: "Gruplar",
    101: "Görünen ad",
    102: "E-posta",
    103: "Kişisel e-posta",
    104: "Şirket e-postası",
    105: "Diğer e-posta",
    106: "Telefon",
    107: "Kişisel Telefon",
    108: "İş Telefonu",
    109: "Cep Telefonu",
    110: "Faks",
    111: "Adres",
    112: "Kişisel Adres",
    113: "İş Adresi",
    114: "Skype",
    115: "Facebook",
    116: "İsim",
    117: "İsim",
    118: "Soyisim",
    119: "Takma İsim",
    120: "Sokak",
    121: "Şehir",
    122: "Eyalet",
    123: "Ülke",
    124: "Posta Kodu",
    125: "Web Sayfası",
    126: "Şirket",
    127: "Departman",
    128: "Ünvan",
    129: "Ofis",
    130: "Doğum günü",
    131: "Notlar",
    132: "Kişiyi düzenle",
    133: "Kişiyi düzenlemekten vazgeç",
    134: "Değişiklikleri kaydet",
    135: "Kişi ekle",
    136: "Grup ekle",
    137: "Grubu düzenle",
    138: "Bu grup bir şirket",
    139: "Grubu düzenlemekten vazgeç",
    140: "Kişiyi sil",
    141: "{contact} silmek istediğinize emin misiniz?",
    142: "Grubu sil",
    143:
        " {group} silmek istediğinize emin misiniz? Gruptaki kişiler silinmeyecektir.",
    144: "Ayarlar",
    145: "Genel",
    146: "24 saat formatı",
    147: "Dil",
    148: "Sistem dili",
    149: "Tema",
    150: "Sistem teması",
    151: "Koyu",
    152: "Açık",
    153: "Senkronizasyon",
    154: "Senkronizasyon sıklığı",
    155: "hiçbir zaman",
    156: "5 dakika",
    157: "30 dakika",
    158: "1 saat",
    159: "2 saat",
    160: "günlük",
    161: "aylık",
    162: "Senkronizasyon periyodu",
    163: "her zaman",
    164: "1 ay",
    165: "3 ay",
    166: "6 ay",
    167: "1 yıl",
    168: "Hesapları yönet",
    169: "Yeni hesap ekle",
    170: "Hesaba tekrar giriş yap",
    171: "Hesabı sil",
    172: " {account} hesabını silmek istediğinize emin misiniz?",
    173: "Hakkında",
    174: " {version} versiyonu",
    175: "Hizmet Şartları",
    176: "Gizlilik Politikası",
    177: "Oturum aç",
    178: "Sil",
    179: "E-postayı açık temada göster",
    180: "Iptal",
    181: "Kapat",
    182: "Spam'e taşı",
    183: "Kaydet",
    184: "Çöpe at",
    185: "Hesap ekle",
    186: "Hepsini göster",
    195: "Lütfen isim girin",
    196: "Lütfen bir e-posta girin",
    198: "Çevrimdışısınız",
    187: "Lütfen mobil uygulama sunucu URL'sini girin",
    188: "Lütfen e-posta adresini girin",
    189: "Lütfen şifrenizi girin",
    190:
        "Bu e-postada alan adı tespit edilemedi, lütfen sunucunuzun URL'sini manuel olarak belirtin.",
    191: "Bu kullanıcının e-posta hesabı yok",
    192: "Bu hesap hesaplar listenizde zaten var.",
    193: "Lütfen alıcı ekleyin",
    194: "Lütfen eklerin yüklenmesi tamamlanıncaya kadar bekleyin",
    197: "Sunucuya bağlanılamadı",
    199: "Bu alanı doldurmak zorunludur",
    200: "E-posta geçerli değil",
    201: "İsim, \"/\\*?<>|:\" karakterleri içeremez",
    202: "Bu isim zaten var",
    203: "Geçersiz anahtar (token)",
    204: "Geçersiz e-posta/şifre",
    205: "Geçersiz giriş parametresi",
    206: "Veri tabanı hatası",
    207: "Lisans sorunu",
    208: "Demo hesabı",
    209: "CAPTCHA hatası",
    210: "Erişim engellendi",
    211: "Bilinmeyen e-posta",
    212: "Kullanıcıya izin verilmiyor",
    213: "Böyle bir kullanıcı zaten var",
    214: "Sistem yapılandırılmamış",
    215: "Modül bulunamadı",
    216: "Yöntem bulunamadı",
    217: "Lisans limiti",
    218: "Ayarlar kaydedilemiyor",
    219: "Şifre değiştirilemiyor",
    220: "Hesabın eski şifresi doğru değil",
    221: "Kişi oluşturulamıyor",
    222: "Grup oluşturulamıyor",
    223: "Kişi güncellenemiyor",
    224: "Grup güncellenemiyor",
    225: "Kişi verileri başka bir uygulama tarafından değiştirildi",
    226: "Kişi verileri alınamıyor",
    227: "Hesap oluşturulamıyor",
    228: "Böyle bir hesap zaten var",
    229: "Diğer REST hatası",
    230: "REST API devre dışı",
    231: "REST bilinmeyen yöntem",
    232: "REST geçersiz parametre",
    233: "REST geçersiz kimlik bilgileri",
    234: "REST geçersiz anahtar",
    235: "REST anahtar süresi doldu",
    236: "REST hesap bulma başarısız",
    237: "REST kullanıcı bulma başarısız oldu",
    238: "Takvimlere izin verilmiyor",
    239: "Dosyalara izin verilmiyor",
    240: "Kişilere izin verilmiyor",
    241: "Yardım masası kullanıcısı zaten var",
    242: "Yardım masası sistemi kullanıcısı zaten var",
    243: "Yardım masası kullanıcısı oluşturulamıyor",
    244: "Bilinmeyen yardım masası kullanıcısı",
    245: "Etkin olmayan Yardım masası kullanıcısı",
    246: "Ses'e izin verilmiyor",
    247: "Yanlış dosya uzantısı",
    248: "Bulut depolama alanı limitinize ulaştınız. Dosya yüklenemiyor.",
    249: "Böyle bir dosya zaten var",
    250: "Dosya bulunamadı",
    251: "Dosya yüklenemiyor: dosya limiti",
    252: "E-posta sunucusu hatası",
    253: "Bilinmeyen hata",
    254: "EEE, d MMM yyyy, HH:mm",
    255: "EEE, d MMM yyyy, HH:mm",
    256: "d MMM yyyy",
    257: "Dün",
    258:
        "Hesabınız iki faktörlü kimlik doğrulamayla korunuyor. \nLütfen PIN kodu girin.",
    259: "PIN",
    260: "PIN'i doğrula",
    261: "Geçersiz PIN",
    262: "Tamam",
    263: "Çıkmak istediğinize emin misiniz?",
    264: "Çıkış",
    265: "OpenPGP",
    266: "Ortak anahtarlar",
    267: "Özel anahtarlar",
    268: "Tüm ortak anahtarları dışa aktar",
    269: "Anahtarları metinden içe aktar",
    270: "Anahtarları dosyadan içe aktar",
    273: "Anahtar oluştur",
    274: "Oluştur",
    275: "Uzunluk",
    276: "İndir",
    277: "Paylaş",
    278: "Ortak anahtar",
    279: "Özel anahtar",
    280: "Anahtarları içe aktar",
    281: "Seçili anahtarları içe aktar",
    282: "Anahtarları kontrol et",
    283: "Anahtarlar bulunamadı",
    284: "Tüm ortak anahtarlar",
    285: "Tümünü indir",
    286: "Tümünü gönder",
    287: "İndiriliyor: {path}",
    288:
        "{user} kullanıcısı için OpenPGP anahtarını silmek istediğinize emin misiniz?",
    289: "İmzala/Şifrele",
    290: "Open PGP İmzala/Şifrele",
    291: "Open PGP Şifresini Çöz",
    292: "İmzala",
    293: "Şifrele",
    295: "Geçersiz şifre",
    296: "{users} kullanıcısı için özel anahtar bulunamadı.",
    300: "İletinin şifresi başarıyla çözüldü ve doğrulandı.",
    301: "İletinin şifresi başarıyla çözüldü ancak doğrulanmadı.",
    302: "Geçersiz anahtar ya da şifre.",
    303: "İletinin şifresi çözülemiyor.",
    304: "İletinizi şifrelemek için en az bir alıcı belirtmeniz gerekli.",
    305: "Doğrula",
    306: "Sistemde zaten bulunan anahtarlar gri işaretlenmiştir.",
    307: "E-postada bul",
    331: "Tamam",
    18: "İletileri sil",
    21: "Bu iletiyi silmek istediğinize emin misiniz?",
    271: "Metinden içe aktar",
    272: "Dosyadan içe aktar",
    297: "PGP'yi geri al",
    308: "Tekrar gönder",
    309: "Çöp kutusunu boşalt",
    310: "Spam'i boşalt",
    311:
        " {folder} dosyasındaki tüm iletileri silmek istediğinize emin misiniz?",
    312: "Kendini yok eden güvenli bir e-posta gönder",
    313: "24 saat",
    314: "72 saat",
    315: "7 gün",
    316: "İleti yaşam süresi",
    317: "İsim yok",
    318: "Veri imzalanmayacak.",
    319: "Veri özel anahtarınızla imzalanacak.",
    320: "Şifre bazlı",
    321: "Anahtar bazlı",
    322: "Şifre bazlı şifreleme kullanılacak.",
    323: "Anahtar bazlı şifreleme kullanılacak.",
    324:
        "Seçili alıcının RGP ortak anahtarı mevcut. Bu ileti bu anahtar kullanılarak şifrelenebilir.",
    325:
        "Seçili alıcının PGP ortak anahtarı yok. Anahtar bazlı şifrelemeye izin verilmez",
    326: "Dijital imza ekle",
    327: "Alıcı seç",
    328:
        "Merhaba,\n{sender} kullanıcısı size kendini yok eden güvenli bir e-posta gönderdi.\nLink üzerinden okuyabilirsiniz:\n{link}\n{message_password} İleti {now} itibariyle {lifeTime} süre için erişilebilir olacaktır",
    329: "Bu ileti şifre korumalıdır. \nŞifre: {password}",
    330: "Güvenli ileti sizinle paylaşıldı",
    332:
        "Kendini yok eden güvenli iletiler yalnızca düz metni destekler. Tüm biçimlendirme kaldırılacaktır. Ayrıca, ekler şifrelenemez ve iletiden kaldırılır.",
    333:
        "Şifre farklı bir kanal üzerinden gönderilmelidir. \n  Şifreyi bir yerde saklayın. Aksi takdirde şifreyi kurtaramazsınız.",
    334: "Kendini yok etme",
    335: "Şifre panoya kopyalandı",
    336: "Faturalandırma planınızda mobil uygulamalara izin verilmiyor.",
    337: "Giriş ekranına geri dön",
    338: "PGP anahtarı geçerli olmayacak",
    339: "Tekrar içe aktar",
    340: "Anahtarı Sil",
    341: "Anahtar Seç",
    342: "Bu anahtarlar kişilere aktarılacak",
    343: "Bu anahtarlar için kişiler oluşturulacak.",
    344: "Anahtarlarınız",
    345: "Ortak anahtar bağlantısı",
    346: "Taşı: ",
    347: "Move",
    348: "Klasöre taşı",
    349: "Gelişmiş arama",
    350: "Gelişmiş arama",
    351: "Metin",
    352: "İtibaren",
    353: "Kadar",
    354: "Uyarı",
    355:
        "Özel PGP anahtarınızı paylaşacaksınız. Anahtar 3. taraflar ile paylaşılmamalıdır. Devam etmek istiyor musunuz?",
    356: "İçe aktar",
    357: " {name} kişiyi vcf'den içe aktar?",
    358: "İleti başlıkları",
    294: "Decrypt",
    298: "Message was successfully verified.",
    299: "Message wasn't verified.",
    361: "This user is already logged in",
    362: "Unread",
    363: "Read",
    364: "Show details",
    365: "Hide details",
    366: "Notifications",
    367: "Device identifier",
    368: "Token storing status",
    369: "Resend Push Token",
    370: "Successful",
    371: "Failed",
    374: "Contacts imported successfully",
    359: "Forward as attachment",
    360: "No name",
    372: "Device id copied to clipboard",
    373: "Discard not saved changes?",
    375: "Encrypt",
    376:
        "If you want messages to this contact to be automatically encrypted and/or signed, check the boxes below. Please note that these messages will be converted to plain text. Attachments will not be encrypted.",
    377: "Delete all",
    378: "Record log in background",
    379: "Show debug view",
    380: "Are you sure you want to delete all logs",
    381: "Counter of uploaded message",
    382: "No PGP public key was found",
    383: "PGP Settings",
    384:
        "The message will be automatically encrypted and/or signed for contacts with OpenPgp keys.\n OpenPGP supports plain text only. All the formatting will be removed before encryption.",
    385: "Not spam",
    386: "password is empty",
    387: "Required password for PGP key",
    388: "Are you sure you want to delete file {name}",
    389: "Can't connect to the server",
  };
  String get(int id) => _map[id];
}
